- hosts: demo
  become: yes
  user: ansible
  tasks:
   - name: Install puppet-agent on slave
     command: sudo yum install https://yum.puppet.com/puppet7-release-el-8.noarch.rpm -y sudo yum -y install puppet-agent

